import test from 'node:test';import assert from 'node:assert/strict';
import {createProject,validateProject} from '../public/modules/session/model.js';
import {createInsert,legacyChain,validateChain} from '../public/modules/audio/chain-config.js';
import {MasterProcessor,processMaster,mixMontage,bakeClipModifiers} from '../public/modules/audio/dsp.js';
import {splitSelected,sliceClip,resizeClip,moveClips,trimClips,insertTime,removeTime,deleteClips,copyClips,pasteClips} from '../public/modules/session/montage.js';
import {prepareSpectralMask,spectralMaskColumn,spectralMaskWeight} from '../public/modules/audio/spectral-mask.js';
import {spectralProcess} from '../public/modules/audio/restoration.js';
const make=()=>{const p=createProject();p.clips=[{...p.clips[0],start:0,offset:0,duration:10,fadeIn:4,fadeOut:4,automation:[{time:0,value:-3},{time:7,value:2},{time:10,value:-2}]}];p.markers=[];return p;};
test('Repeated inserts preserve render across arbitrary blocks and dry latency',()=>{const p=createProject(),gain=createInsert('gain','g'),lim=createInsert('limiter','l');gain.params.gain=12;lim.wet=.37;p.effects.chain=[gain,lim,{...gain,id:'g2'},{...lim,id:'l2'}];const x=Float32Array.from({length:5013},(_,i)=>Math.sin(i*.04)*.2),expected=processMaster([x,x],48000,p.effects);for(const block of [1,127,128,4096]){const proc=new MasterProcessor(48000,2,p.effects),data=[new Float32Array(x.length+proc.delay),new Float32Array(x.length+proc.delay)];data.forEach(c=>c.set(x));const out=data.map(c=>new Float32Array(c.length));for(let at=0;at<data[0].length;at+=block)proc.process(data.map(c=>c.subarray(at,at+block)),out.map(c=>c.subarray(at,at+block)));assert.deepEqual(out[0].slice(proc.delay),expected[0]);}const dry={chain:[{...lim,wet:0},{...lim,id:'l3',wet:0}]};assert.deepEqual(processMaster([x],48000,dry)[0],x);});
test('Insert ordering, mono identity and configuration validation',()=>{const gain=createInsert('gain','g'),lim=createInsert('limiter','l');gain.params.gain=12;const x=new Float32Array(4000).fill(.5);assert.ok(processMaster([x],48000,{chain:[gain,lim]})[0][3999]<.9);assert.ok(processMaster([x],48000,{chain:[lim,gain]})[0][3999]>1.9);assert.throws(()=>validateChain([{...gain,type:['gain']}]));const proc=new MasterProcessor(48000,2,{chain:[]}),out=[new Float32Array(2),new Float32Array(2)];proc.process([new Float32Array([.2,.3])],out);assert.deepEqual(out[0],out[1]);const hp=createInsert('highpass','hp');const filtered=processMaster([new Float32Array([NaN,1,1,1])],48000,{chain:[hp]})[0];assert.ok(filtered[1]>.5);});
test('Split retains source fades and automation; resulting audio matches sample for sample',()=>{const p=make(),source={sampleRate:8000,channels:[new Float32Array(80000).fill(.2),new Float32Array(80000).fill(.2)]},assets=new Map([[p.clips[0].assetId,source]]),before=mixMontage(p,assets,8000,0,10);splitSelected(p,[p.clips[0].id],2.5);validateProject(p);const after=mixMontage(p,assets,8000,0,10);for(let i=0;i<before[0].length;i++)assert.ok(Math.abs(before[0][i]-after[0][i])<1e-7);});
test('Overlapping ripple trim closes union once and collapses markers',()=>{const p=make(),c=p.clips[0];p.clips.push({...c,id:'second'},{...c,id:'follower',start:10,duration:1,automation:[]});p.markers=[{id:'m',name:'M',time:8,color:'#abcdef'}];trimClips(p,[c.id,'second'],0,5,{ripple:'all'});assert.equal(p.clips[2].start,5);assert.equal(p.markers[0].time,5);});
test('Ripple per-track followers, maximum bounds and marker collapse',()=>{const p=make(),c=p.clips[0];p.tracks.push({...p.tracks[0],id:'t2'});p.clips=[{...c,duration:3},{...c,id:'b',trackId:'t2'},{...c,id:'f',start:4,duration:1}];moveClips(p,[c.id,'b'],2,0,{ripple:'tracks'});assert.equal(p.clips[2].start,6);p.markers=[{id:'m',time:86399}];assert.equal(moveClips(p,[c.id,'b'],3,0,{ripple:'all'}).delta,1);assert.throws(()=>insertTime(p,0,2));const q=make();q.markers=[{id:'a',time:9},{id:'b',time:10}];deleteClips(q,[q.clips[0].id],{ripple:'all'});assert.deepEqual(q.markers.map(m=>m.time),[0,0]);});
test('Time insertion and removal preserve crossing clip content and group copy layout',()=>{const p=make(),id=p.clips[0].id;insertTime(p,3,2);assert.equal(p.clips.length,2);assert.equal(p.clips[1].start,5);assert.equal(p.clips[1].offset,3);removeTime(p,3,5);assert.equal(p.clips[1].start,3);const copied=copyClips(p,p.clips.map(c=>c.id));const ids=pasteClips(p,copied,12,p.tracks[0].id);assert.equal(ids.length,2);assert.equal(p.clips[2].start,12);assert.equal(p.clips[3].start,15);});
test('Brush capsule boundary includes both vertical sides and subtract mask holes',()=>{const mask={nyquist:24000,shapes:[{type:'brush',operation:'add',radiusTime:1,radiusFrequency:.1,points:[{time:2,hz:.3**2*24000},{time:2,hz:.7**2*24000}]}]},p=prepareSpectralMask(mask);for(const t of [1,2,3])assert.equal(spectralMaskWeight(spectralMaskColumn(p,t),.5**2*24000,24000),1);mask.shapes.push({type:'rectangle',operation:'subtract',points:[{time:1.5,hz:5000},{time:2.5,hz:7000}]});assert.equal(spectralMaskWeight(spectralMaskColumn(prepareSpectralMask(mask),2),6000,24000),0);});
test('Empty spectral mask is identity; polygon attenuation changes selected frequency bins',()=>{const rate=8000,x=Float32Array.from({length:8000},(_,i)=>.2*Math.sin(i*2*Math.PI*1000/rate)),empty={nyquist:4000,shapes:[]};const out=spectralProcess([x],rate,{operation:'attenuate',start:0,end:1,amount:-30,mask:empty})[0];for(let i=0;i<x.length;i++)assert.ok(Math.abs(x[i]-out[i])<1e-7);const mask={nyquist:4000,shapes:[{type:'polygon',operation:'add',points:[{time:.2,hz:600},{time:.8,hz:600},{time:.8,hz:1400},{time:.2,hz:1400}]}]};const wet=spectralProcess([x],rate,{operation:'attenuate',start:.2,end:.8,amount:-30,fftSize:256,mask})[0];assert.ok(Math.abs(wet[4001])<Math.abs(x[4001])*.1);assert.equal(wet[100],x[100]);});
const {mergeProject}=await import('../public/modules/session/merge.js');
test('Insert merge preserves an ordinary save order and concurrent insertion runs',()=>{const p=createProject();p.effects.chain=[createInsert('gain','base')];const a=structuredClone(p);a.effects.chain.push(createInsert('gain','z-gain'),createInsert('limiter','a-limit'));let m=mergeProject(p,a,p);assert.deepEqual(m.conflicts,[]);assert.deepEqual(m.project.effects.chain.map(n=>n.id),['base','z-gain','a-limit']);const b=structuredClone(p);b.effects.chain.push(createInsert('gain','x-gain'),createInsert('limiter','c-limit'));m=mergeProject(p,a,b);assert.deepEqual(m.conflicts,[]);const ids=m.project.effects.chain.map(n=>n.id);assert.ok(ids.indexOf('z-gain')<ids.indexOf('a-limit'));assert.ok(ids.indexOf('x-gain')<ids.indexOf('c-limit'));});
test('Independent insert parameter edits merge; native identity and state edits conflict',()=>{const p=createProject();p.effects.chain=[createInsert('eq','eq')];let a=structuredClone(p),b=structuredClone(p);a.effects.chain[0].params.low=2;b.effects.chain[0].params.high=-2;let m=mergeProject(p,a,b);assert.deepEqual(m.conflicts,[]);assert.equal(m.project.effects.chain[0].params.low,2);assert.equal(m.project.effects.chain[0].params.high,-2);p.effects.chain=[{...createInsert('native','native'),params:{pluginId:'one',state:'AAAA',parameters:[]}}];a=structuredClone(p);b=structuredClone(p);a.effects.chain[0].params.pluginId='two';b.effects.chain[0].params.state='BBBB';m=mergeProject(p,a,b);assert.ok(m.conflicts.some(c=>c.path==='effects.chain.native.$content'));});
test('Repeated source slicing preserves original fade domain and full slice is unchanged',()=>{const c=make().clips[0],a=sliceClip(c,1,8),b=sliceClip(a,0,4);assert.deepEqual(b.fadeSource,a.fadeSource);assert.deepEqual(sliceClip(c,0,c.duration),c);});

test('Outward trim restores trimmed source, fade and envelope coordinates',()=>{const p=make(),original=structuredClone(p.clips[0]);trimClips(p,[original.id],2,8);resizeClip(p,original.id,-2,8,10);validateProject(p);assert.equal(p.clips[0].start,0);assert.equal(p.clips[0].offset,0);assert.equal(p.clips[0].duration,10);assert.equal(p.clips[0].fadeSource.offset,0);const q=make();q.clips.push({...q.clips[0],id:'follow',start:12,duration:1,automation:[]});q.clips[0].duration=5;resizeClip(q,q.clips[0].id,0,7,10,{ripple:'all'});assert.equal(q.clips[1].start,14);});

test('Baked clip modifiers preserve split fades and automation for timeline-changing processing',()=>{const p=make();splitSelected(p,[p.clips[0].id],2.5);const c=p.clips[1],sr=8000,source=[new Float32Array(Math.round(c.duration*sr)).fill(.2),new Float32Array(Math.round(c.duration*sr)).fill(.2)];const baked=bakeClipModifiers(source.map(c=>c.slice()),c,sr);const assets=new Map([[c.assetId,{sampleRate:sr,channels:[new Float32Array(80000).fill(.2),new Float32Array(80000).fill(.2)]}]]);p.clips=[c];const expected=mixMontage(p,assets,sr,c.start,c.start+c.duration);for(let i=0;i<baked[0].length;i++)assert.ok(Math.abs(baked[0][i]-expected[0][i])<1e-7);});

test('Spectrogram windows cover long viewport with bounded concurrent source reads',async()=>{const {readSpectrogramWindows}=await import('../public/modules/audio/streaming.js');let active=0,max=0,framesRead=0;const asset={channels:[{}],provider:{async readFrames(start,count){active++;max=Math.max(max,active);framesRead+=count;await Promise.resolve();active--;return [new Float32Array(count).fill(start)];}}};const result=await readSpectrogramWindows(asset,100,48000*3600,800);assert.ok(max<=4);assert.equal(framesRead,800*1024);assert.equal(result.channels[0][0],100);assert.ok(result.channels[0].at(-1)>48000*3500);await assert.rejects(readSpectrogramWindows(asset,0,1024,20,{isCanceled:()=>true}),{name:'AbortError'});});
