import test from 'node:test';import assert from 'node:assert/strict';import {spawn,spawnSync} from 'node:child_process';import {once} from 'node:events';import {mkdtemp,writeFile,readFile,rm,access} from 'node:fs/promises';import path from 'node:path';import {tmpdir} from 'node:os';import {encodeWav,decodeWav} from '../public/modules/audio/wav.js';
const root=path.resolve(import.meta.dirname,'..');let built=true;try{await access(path.join(root,'native/build/auralis-clap'));}catch{built=false;}
const decode=b=>decodeWav(b.buffer.slice(b.byteOffset,b.byteOffset+b.length));
for(const [format,ext]of [['clap','clap'],['vst3','so']]){
 test(format+' saved state round trip, parameter override and wrong-identity rejection',{skip:!built},async()=>{const dir=await mkdtemp(path.join(tmpdir(),'auralis-state-'));try{const host=path.join(root,'native/build/auralis-'+format),plugin=path.join(root,'native/build/gain-fixture.'+ext),input=path.join(dir,'in.wav'),output=path.join(dir,'out.wav'),state=path.join(dir,'state.bin');await writeFile(input,new Uint8Array(encodeWav([new Float32Array(1001).fill(.4),new Float32Array(1001).fill(-.4)],48000,{bits:32,float:true})));let r=spawnSync(host,[plugin,input,output,'0=0.25','--state-out',state],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);r=spawnSync(host,[plugin,input,output,'--state-in',state],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.ok(Math.abs(decode(await readFile(output)).channels[0][500]-.1)<1e-7);r=spawnSync(host,[plugin,input,output,'--state-in',state,'0=0.75'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.ok(Math.abs(decode(await readFile(output)).channels[0][500]-.3)<1e-7);const b=await readFile(state);b[12]^=1;await writeFile(state,b);r=spawnSync(host,[plugin,input,output,'--state-in',state],{encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/different plug-in/);}finally{await rm(dir,{recursive:true,force:true});}});
 test(format+' native X11 editor gesture persists DSP and reopens state',{skip:!built||!process.env.AURALIS_TEST_DISPLAY},async()=>{const dir=await mkdtemp(path.join(tmpdir(),'auralis-editor-test-')),env={...process.env,DISPLAY:process.env.AURALIS_TEST_DISPLAY};let child;try{const host=path.join(root,'native/build/auralis-'+format),plugin=path.join(root,'native/build/gain-fixture.'+ext),state=path.join(dir,'after.bin');async function editor(args){child=spawn(host,[plugin,'--edit','--state-out',state,...args],{env,stdio:['pipe','pipe','pipe']});let logs='';await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Editor startup timed out: '+logs)),10000);child.stdout.on('data',b=>{logs+=b;if(logs.includes('EDITOR_READY')){clearTimeout(timer);resolve();}});child.stderr.on('data',b=>logs+=b);child.on('exit',code=>{clearTimeout(timer);if(!logs.includes('EDITOR_READY'))reject(Error('Editor exit '+code+': '+logs));});});}
 await editor([]);const xdo=process.env.AURALIS_XDOTOOL||'xdotool',title=format==='clap'?'Auralis test gain':'Auralis VST3 editor';let r=spawnSync(xdo,['search','--name','^'+title+'$'],{env,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);const window=r.stdout.trim().split('\n').at(-1);r=spawnSync(xdo,['mousemove','--window',window,'100','70','click','1'],{env,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);await new Promise(r=>setTimeout(r,100));if(format==='vst3'){const geometry=spawnSync(xdo,['getwindowgeometry','--shell',window],{env,encoding:'utf8'});assert.match(geometry.stdout,/WIDTH=600/);assert.match(geometry.stdout,/HEIGHT=240/);}child.stdin.write('save\n');const [code]=await once(child,'exit');assert.equal(code,0);child=null;const saved=await readFile(state);assert.ok(saved.length>24);const input=path.join(dir,'in.wav'),out=path.join(dir,'out.wav');await writeFile(input,new Uint8Array(encodeWav([new Float32Array(1001).fill(.4),new Float32Array(1001).fill(.4)],48000,{bits:32,float:true})));r=spawnSync(host,[plugin,input,out,'--state-in',state],{env,encoding:'utf8',timeout:10000});assert.equal(r.status,0,r.stderr);assert.ok(Math.abs(decode(await readFile(out)).channels[0][500]-(format==='clap'?.31:.3))<1e-6,'GUI edit must change DSP');await editor(['--state-in',state]);child.stdin.write('save\n');assert.equal((await once(child,'exit'))[0],0);child=null;assert.deepEqual(await readFile(state),saved);
 }finally{if(child&&child.exitCode===null){child.kill('SIGKILL');await once(child,'exit').catch(()=>{});}await rm(dir,{recursive:true,force:true});}});
}
