import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { SQLiteAdapter } from '../server/local-adapters.mjs';
import { handleApi, validateDocument } from '../server/api.js';
import { createProject } from '../public/modules/session/model.js';
import { encodeWav } from '../public/modules/audio/wav.js';
async function fixture() {
    const db = new SQLiteAdapter();
    for (const f of (await readdir(new URL('../drizzle/', import.meta.url))).filter(f => f.endsWith('.sql')))
        db.sqlite.exec(await readFile(new URL('../drizzle/' + f, import.meta.url), 'utf8'));
    const blobs = new Map();
    const BUCKET = { async put(key, v) { blobs.set(key, new Uint8Array(v).slice()); }, async get(key) { return blobs.has(key) ? { body: blobs.get(key) } : null; }, async delete(key) { blobs.delete(key); } };
    const call = async (path, method = 'GET', body, user = 'owner', origin = 'https://studio.test', extraHeaders = {}) => { const bytes = body instanceof ArrayBuffer; return handleApi(new Request('https://studio.test/api/' + path, { method, headers: { 'oai-authenticated-user-id': user, 'oai-authenticated-user-email': user + '@test.invalid', origin, 'content-type': bytes ? 'audio/wav' : 'application/json', ...extraHeaders }, body: body === undefined ? undefined : bytes ? body : JSON.stringify(body) }), { DB: db, BUCKET }); };
    const created = await (await call('projects', 'POST', { project: createProject() })).json();
    return { db, blobs, BUCKET, call, p: created.project };
}
test('Create/save/reopen persists exact revision and version history', async () => { const f = await fixture(); f.p.name = 'Updated session'; const r = await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 }); assert.equal(r.status, 200); const loaded = await (await f.call('projects/' + f.p.id)).json(); assert.equal(loaded.project.name, 'Updated session'); assert.equal(loaded.project.revision, 2); const v = await (await f.call('projects/' + f.p.id + '/versions')).json(); assert.equal(v.length, 2); f.db.close(); });
test('Stale save returns 409 and does not add a version', async () => { const f = await fixture(); assert.equal((await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 })).status, 200); assert.equal((await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 })).status, 409); assert.equal((await (await f.call('projects/' + f.p.id + '/versions')).json()).length, 2); f.db.close(); });
test('Guarded save and history insert roll back together', async () => {
    const f = await fixture();
    f.db.sqlite.exec("CREATE TRIGGER fail_history BEFORE INSERT ON versions WHEN NEW.revision=2 BEGIN SELECT RAISE(ABORT, 'test failure'); END");
    const old = console.error;
    console.error = () => { };
    try {
        assert.equal((await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 })).status, 500);
    }
    finally {
        console.error = old;
    }
    assert.equal((await (await f.call('projects/' + f.p.id)).json()).project.revision, 1);
    f.db.close();
});
test('Cross-project access and cross-origin writes are denied', async () => { const f = await fixture(); assert.equal((await f.call('projects/' + f.p.id, 'GET', undefined, 'stranger')).status, 404); assert.equal((await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 }, 'owner', 'https://evil.test')).status, 403); f.db.close(); });
test('Single-use viewer invitation grants read but rejects edits and comments', async () => { const f = await fixture(); const inv = await (await f.call('projects/' + f.p.id + '/invite', 'POST', { role: 'viewer' })).json(); assert.equal((await f.call('join', 'POST', { token: inv.token }, 'viewer')).status, 200); assert.equal((await f.call('join', 'POST', { token: inv.token }, 'other')).status, 404); assert.equal((await f.call('projects/' + f.p.id, 'GET', undefined, 'viewer')).status, 200); assert.equal((await f.call('projects/' + f.p.id, 'PUT', { project: f.p, revision: 1 }, 'viewer')).status, 403); assert.equal((await f.call('projects/' + f.p.id + '/comments', 'POST', { text: 'test', time: 1 }, 'viewer')).status, 403); f.db.close(); });
test('Concurrent invitation consumers receive only one success', async () => { const f = await fixture(); const inv = await (await f.call('projects/' + f.p.id + '/invite', 'POST', { role: 'editor' })).json(); const r = await Promise.all([f.call('join', 'POST', { token: inv.token }, 'a'), f.call('join', 'POST', { token: inv.token }, 'b')]); assert.equal(r.filter(x => x.status === 200).length, 1); f.db.close(); });
test('Existing members cannot consume another invitation', async () => { const f = await fixture(); const inv = await (await f.call('projects/' + f.p.id + '/invite', 'POST', { role: 'viewer' })).json(); assert.equal((await f.call('join', 'POST', { token: inv.token })).status, 409); assert.equal((await f.call('join', 'POST', { token: inv.token }, 'new')).status, 200); f.db.close(); });
test('Audio assets are immutable, scoped and uncached', async () => { const f = await fixture(), url = 'projects/' + f.p.id + '/assets/test-source', a = encodeWav([Float32Array.of(.2, .3)], 48000, { bits: 32, float: true }), b = encodeWav([Float32Array.of(.9, .4)], 48000, { bits: 32, float: true }); assert.equal((await f.call(url, 'PUT', a)).status, 200); assert.equal((await f.call(url, 'PUT', a)).status, 200); assert.equal((await f.call(url, 'PUT', b)).status, 409); assert.equal((await f.call(url, 'GET', undefined, 'stranger')).status, 404); const r = await f.call(url); assert.equal(r.headers.get('cache-control'), 'private, no-store'); assert.deepEqual(await r.arrayBuffer(), a); f.db.close(); });
test('Concurrent different uploads cannot change the winning source', async () => { const f = await fixture(), url = 'projects/' + f.p.id + '/assets/race', a = encodeWav([Float32Array.of(.2)], 48000, { bits: 32, float: true }), b = encodeWav([Float32Array.of(.9)], 48000, { bits: 32, float: true }); const r = await Promise.all([f.call(url, 'PUT', a), f.call(url, 'PUT', b)]); assert.equal(r.filter(x => x.status === 200).length, 1); assert.equal(r.filter(x => x.status === 409).length, 1); assert.equal(f.blobs.size, 1); f.db.close(); });
test('Malformed WAV and malformed project fields are rejected', async () => {
    const f = await fixture();
    assert.equal((await f.call('projects/' + f.p.id + '/assets/bad', 'PUT', new ArrayBuffer(44))).status, 400);
    for (const change of [p => p.assets[0].name = {}, p => p.sampleRate = -1, p => p.assets.push(p.assets[0]), p => p.clips[0].duration = 0, p => p.clips[0].offset = 100, p => p.effects.preset = {}]) {
        const p = createProject();
        change(p);
        assert.throws(() => validateDocument(p));
    }
    f.db.close();
});
test('Comment author and owner are the only resolvers', async () => { const f = await fixture(); const inv = await (await f.call('projects/' + f.p.id + '/invite', 'POST', { role: 'commenter' })).json(); await f.call('join', 'POST', { token: inv.token }, 'commenter'); const c = await (await f.call('projects/' + f.p.id + '/comments', 'POST', { text: 'Check the tail', time: 46 })).json(); assert.equal((await f.call('projects/' + f.p.id + '/comments', 'PATCH', { id: c.id, resolved: true }, 'commenter')).status, 403); assert.equal((await f.call('projects/' + f.p.id + '/comments', 'PATCH', { id: c.id, resolved: true })).status, 200); f.db.close(); });
test('Independent edits merge automatically from a trusted base', async () => { const f = await fixture(), a = structuredClone(f.p), b = structuredClone(f.p); a.name = 'Merged name'; b.tracks[0].gain = -3; const save = p => f.call('projects/' + p.id, 'PUT', { project: p, baseRevision: 1, operationId: crypto.randomUUID() }); assert.equal((await save(a)).status, 200); const r = await (await save(b)).json(); assert.equal(r.merged, true); assert.equal(r.project.name, 'Merged name'); assert.equal(r.project.tracks[0].gain, -3); f.db.close(); });
test('Overlapping edits preserve proposal and explicit resolution', async () => { const f = await fixture(), a = structuredClone(f.p), b = structuredClone(f.p); a.name = 'First'; b.name = 'Second'; await f.call('projects/' + a.id, 'PUT', { project: a, baseRevision: 1, operationId: crypto.randomUUID() }); const conflict = await f.call('projects/' + b.id, 'PUT', { project: b, baseRevision: 1, operationId: crypto.randomUUID() }); assert.equal(conflict.status, 409); const info = await conflict.json(); assert.equal(info.code, 'MERGE_CONFLICT'); assert.ok(info.conflicts.some(c => c.path === 'name')); const resolved = await f.call('projects/' + b.id + '/conflicts/' + info.proposalId + '/resolve', 'POST', { headRevision: 2, operationId: crypto.randomUUID(), choices: { name: 'incoming' } }); assert.equal(resolved.status, 200); assert.equal((await resolved.json()).project.name, 'Second'); f.db.close(); });
test('Concurrent identical operation retries commit exactly once with one audit event', async () => { const f = await fixture(), input = { project: f.p, baseRevision: 1, operationId: crypto.randomUUID() }; const results = await Promise.all(Array.from({ length: 12 }, () => f.call('projects/' + f.p.id, 'PUT', input))); assert.ok(results.every(r => r.status === 200)); assert.equal(f.db.sqlite.prepare('SELECT revision FROM projects').get().revision, 2); assert.equal(f.db.sqlite.prepare("SELECT COUNT(*) AS n FROM audit_events WHERE action='project.commit'").get().n, 1); f.db.close(); });
test('Same operation id with different concurrent content cannot commit twice', async () => { const f = await fixture(), a = structuredClone(f.p), b = structuredClone(f.p), op = crypto.randomUUID(); a.name = 'A'; b.tracks[0].gain = -4; const r = await Promise.all([a, b].map(project => f.call('projects/' + project.id, 'PUT', { project, baseRevision: 1, operationId: op }))); assert.equal(r.filter(x => x.status === 200).length, 1); assert.equal(r.filter(x => x.status === 409).length, 1); assert.equal(f.db.sqlite.prepare('SELECT revision FROM projects').get().revision, 2); f.db.close(); });
test('Source and trim edits conflict as one coupled clip group', async () => { const f = await fixture(), a = structuredClone(f.p), b = structuredClone(f.p); a.clips[0].offset = .1; a.clips[0].duration = 47.9; b.clips[0].fadeIn = 1; await f.call('projects/' + a.id, 'PUT', { project: a, baseRevision: 1, operationId: crypto.randomUUID() }); const r = await f.call('projects/' + b.id, 'PUT', { project: b, baseRevision: 1, operationId: crypto.randomUUID() }); assert.equal(r.status, 409); assert.ok((await r.json()).conflicts.some(c => c.path.endsWith('$content'))); f.db.close(); });
test('Track ordering survives an independent concurrent metadata edit', async () => { const f = await fixture(), a = structuredClone(f.p), b = structuredClone(f.p); a.name = 'Title'; b.tracks.reverse(); await f.call('projects/' + a.id, 'PUT', { project: a, baseRevision: 1, operationId: crypto.randomUUID() }); const r = await (await f.call('projects/' + b.id, 'PUT', { project: b, baseRevision: 1, operationId: crypto.randomUUID() })).json(); assert.equal(r.project.tracks[0].id, 'track-2'); f.db.close(); });
test('Admin revocation, archive, quotas and audit enforce owner scope', async () => { const f = await fixture(), url = 'projects/' + f.p.id; const inv = await (await f.call(url + '/invite', 'POST', { role: 'editor' })).json(); await f.call('join', 'POST', { token: inv.token }, 'editor'); assert.equal((await f.call(url + '/admin', 'GET', undefined, 'editor')).status, 403); assert.equal((await f.call(url + '/admin', 'PATCH', { userId: 'editor', role: 'revoke' })).status, 200); assert.equal((await f.call(url, 'GET', undefined, 'editor')).status, 404); assert.equal((await f.call(url + '/admin', 'PATCH', { archived: true })).status, 200); assert.equal((await f.call(url, 'PUT', { project: f.p, baseRevision: 1, operationId: crypto.randomUUID() })).status, 403); const admin = await (await f.call(url + '/admin')).json(); assert.equal(admin.settings.permission_epoch, 2); assert.equal(admin.events.length, 3); assert.equal((await f.call(url + '/admin', 'PATCH', { archived: false })).status, 200); f.db.close(); });
test('Chunk upload validates completeness, immutability and byte ranges', async () => { const f = await fixture(), base = 'projects/' + f.p.id + '/assets/chunked', x = new Float32Array(300000).fill(.125), wav = encodeWav([x, x], 48000, { bits: 32, float: true }); const u = await (await f.call(base + '/upload', 'POST', { size: wav.byteLength, name: 'Large.wav' })).json(); assert.ok(u.parts > 1); assert.equal((await f.call(base + '/upload/' + u.uploadId + '/complete', 'POST', {})).status, 409); for (let i = 0; i < u.parts; i++)
    assert.equal((await f.call(base + '/upload/' + u.uploadId + '/' + i, 'PUT', wav.slice(i * u.chunkSize, (i + 1) * u.chunkSize))).status, 200); assert.equal((await f.call(base + '/upload/' + u.uploadId + '/complete', 'POST', {})).status, 200); const response = await f.call(base); assert.equal(response.status, 200); assert.deepEqual(await response.arrayBuffer(), wav); const range = await f.call(base, 'GET', undefined, 'owner', 'https://studio.test', { Range: 'bytes=2097148-2097160' }); assert.equal(range.status, 206); assert.deepEqual(await range.arrayBuffer(), wav.slice(2097148, 2097161)); assert.equal(range.headers.get('content-range'), 'bytes 2097148-2097160/' + wav.byteLength); f.db.close(); });
test('Audit insertion failure rolls back commit, receipt, history and tombstone', async () => { const f = await fixture(); f.db.sqlite.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'test');END"); const old = console.error; console.error = () => { }; try {
    const p = structuredClone(f.p);
    p.markers.pop();
    assert.equal((await f.call('projects/' + p.id, 'PUT', { project: p, baseRevision: 1, operationId: crypto.randomUUID() })).status, 500);
}
finally {
    console.error = old;
} assert.equal(f.db.sqlite.prepare('SELECT revision FROM projects').get().revision, 1); for (const table of ['operations', 'entity_tombstones'])
    assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) AS n FROM ' + table).get().n, 0); f.db.close(); });
test('Resolution of edit/delete restores deliberately and retries idempotently', async () => { const f = await fixture(), deleted = structuredClone(f.p), edited = structuredClone(f.p); deleted.clips = []; edited.clips[0].name = 'Restored edit'; await f.call('projects/' + f.p.id, 'PUT', { project: deleted, baseRevision: 1, operationId: crypto.randomUUID() }); const conflict = await (await f.call('projects/' + f.p.id, 'PUT', { project: edited, baseRevision: 1, operationId: crypto.randomUUID() })).json(), input = { headRevision: 2, operationId: crypto.randomUUID(), choices: { 'clips.clip-demo': 'incoming' } }, url = 'projects/' + f.p.id + '/conflicts/' + conflict.proposalId + '/resolve'; const result = await f.call(url, 'POST', input); assert.equal(result.status, 200); assert.equal((await result.json()).project.clips[0].name, 'Restored edit'); const retry = await f.call(url, 'POST', input); assert.equal(retry.status, 200); assert.equal((await retry.json()).project.revision, 3); f.db.close(); });
test('Revocation during a delayed asset upload prevents commit and removes staged bytes', async () => { const f = await fixture(), url = 'projects/' + f.p.id; const inv = await (await f.call(url + '/invite', 'POST', { role: 'editor' })).json(); await f.call('join', 'POST', { token: inv.token }, 'editor'); const wav = new Uint8Array(encodeWav([new Float32Array(100)], 48000, { bits: 32, float: true })); let unblock, started; const blocked = new Promise(r => unblock = r), reading = new Promise(r => started = r); let count = 0; const stream = new ReadableStream({ async pull(controller) { if (count++ === 0) {
        controller.enqueue(wav.subarray(0, 100));
        return;
    } started(); await blocked; controller.enqueue(wav.subarray(100)); controller.close(); } }); const pending = handleApi(new Request('https://studio.test/api/' + url + '/assets/delayed', { method: 'PUT', headers: { 'oai-authenticated-user-id': 'editor', 'content-type': 'audio/wav' }, body: stream, duplex: 'half' }), { DB: f.db, BUCKET: f.BUCKET }); await reading; await f.call(url + '/admin', 'PATCH', { userId: 'editor', role: 'revoke' }); unblock(); const result = await pending; assert.ok([403, 409].includes(result.status)); assert.equal(f.db.sqlite.prepare('SELECT COUNT(*) AS n FROM assets').get().n, 0); assert.equal(f.blobs.size, 0); f.db.close(); });
