#include "state.hpp"
#include "x11-window.hpp"
#include <dlfcn.h>
#include <atomic>
#include <thread>
#include <clap/clap.h>
#include <clap/ext/thread-check.h>
#include <clap/ext/audio-ports.h>
#include <clap/ext/latency.h>
#include <clap/ext/render.h>
#include <clap/ext/params.h>
#include <clap/ext/state.h>
#include <clap/ext/gui.h>
#include <clap/ext/timer-support.h>
#include <clap/ext/posix-fd-support.h>
struct HostState{std::atomic<bool>audio{false},callback{false},restart{false},flush{false},closed{false};std::thread::id main=std::this_thread::get_id();
#ifdef AURALIS_X11
 NativeWindow*window=nullptr;std::atomic<uint64_t>sizeRequest{0};std::atomic<int>visibility{0};struct Timer{uint32_t period;uint64_t next;};std::map<clap_id,Timer>timers;std::map<int,clap_posix_fd_flags_t>fds;clap_id nextTimer=1;
#endif
};static HostState state;
static const clap_host_thread_check_t threadCheck={[](const clap_host_t*){return std::this_thread::get_id()==state.main;},[](const clap_host_t*){return state.audio&&std::this_thread::get_id()==state.main;}};
static const clap_host_params_t hostParams={[](const clap_host_t*,clap_param_rescan_flags){},[](const clap_host_t*,clap_id,clap_param_clear_flags){},[](const clap_host_t*){state.flush=true;}};
static const clap_host_state_t hostState={[](const clap_host_t*){}};
#ifdef AURALIS_X11
static const clap_host_gui_t hostGui={[](const clap_host_t*){},[](const clap_host_t*,uint32_t w,uint32_t h){if(w<16||h<16||w>8192||h>8192)return false;state.sizeRequest=(uint64_t(w)<<32)|h;return true;},[](const clap_host_t*){state.visibility=1;return true;},[](const clap_host_t*){state.visibility=2;return true;},[](const clap_host_t*,bool){state.closed=true;}};
static const clap_host_timer_support_t hostTimers={[](const clap_host_t*,uint32_t ms,clap_id*out){if(!out||state.timers.size()>=128)return false;*out=state.nextTimer++;state.timers[*out]={std::max(1u,ms),monotonicMs()+std::max(1u,ms)};return true;},[](const clap_host_t*,clap_id id){return bool(state.timers.erase(id));}};
static const clap_host_posix_fd_support_t hostFDs={[](const clap_host_t*,int fd,clap_posix_fd_flags_t f){if(fd<0||state.fds.size()>=128||state.fds.count(fd))return false;state.fds[fd]=f;return true;},[](const clap_host_t*,int fd,clap_posix_fd_flags_t f){if(!state.fds.count(fd))return false;state.fds[fd]=f;return true;},[](const clap_host_t*,int fd){return bool(state.fds.erase(fd));}};
#endif
static const void* extension(const clap_host_t*,const char*id){if(!strcmp(id,CLAP_EXT_THREAD_CHECK))return &threadCheck;if(!strcmp(id,CLAP_EXT_PARAMS))return &hostParams;if(!strcmp(id,CLAP_EXT_STATE))return &hostState;
#ifdef AURALIS_X11
 if(!strcmp(id,CLAP_EXT_GUI))return &hostGui;if(!strcmp(id,CLAP_EXT_TIMER_SUPPORT))return &hostTimers;if(!strcmp(id,CLAP_EXT_POSIX_FD_SUPPORT))return &hostFDs;
#endif
 return nullptr;}
struct StateStream{std::vector<unsigned char>bytes;size_t at=0;};
static void load(const clap_plugin_t*p,const NativeState&s){if(s.component.empty())return;auto*ext=(const clap_plugin_state_t*)p->get_extension(p,CLAP_EXT_STATE);require(ext,"Plug-in has no state support");StateStream data{s.component,0};clap_istream_t stream{&data,[](const clap_istream_t*s,void*b,uint64_t n)->int64_t{auto*d=(StateStream*)s->ctx;auto count=std::min<uint64_t>(n,d->bytes.size()-d->at);memcpy(b,d->bytes.data()+d->at,count);d->at+=count;return count;}};require(ext->load(p,&stream),"Plug-in rejected state");}
static void save(const clap_plugin_t*p,NativeState&s,const std::string&path){auto*ext=(const clap_plugin_state_t*)p->get_extension(p,CLAP_EXT_STATE);require(ext,"Plug-in has no serializable state");StateStream data;clap_ostream_t stream{&data,[](const clap_ostream_t*s,const void*b,uint64_t n)->int64_t{auto*d=(StateStream*)s->ctx;if(n>MAX_STATE||d->bytes.size()+n>MAX_STATE)return -1;auto*bytes=(const unsigned char*)b;d->bytes.insert(d->bytes.end(),bytes,bytes+n);return n;}};require(ext->save(p,&stream),"Plug-in state save failed");s.component=std::move(data.bytes);writeState(path,s);}
int main(int argc,char**argv){try{HostOptions options(argc,argv);void*lib=dlopen(argv[1],RTLD_NOW|RTLD_LOCAL);require(lib,"Cannot load CLAP library");const auto*entry=(const clap_plugin_entry_t*)dlsym(lib,"clap_entry");require(entry&&clap_version_is_compatible(entry->clap_version)&&entry->init(argv[1]),"CLAP entry init failed");auto*factory=(const clap_plugin_factory_t*)entry->get_factory(CLAP_PLUGIN_FACTORY_ID);require(factory&&factory->get_plugin_count(factory)>0,"No CLAP plug-ins");const clap_plugin_descriptor_t*descriptor=nullptr;for(uint32_t i=0;i<factory->get_plugin_count(factory);i++){auto*d=factory->get_plugin_descriptor(factory,i);if(d&&(options.pluginId.empty()||options.pluginId==d->id)){descriptor=d;break;}}require(descriptor,"Configured CLAP identity not found");clap_host_t host={CLAP_VERSION,&state,"Auralis Native","Auralis","https://auralis-studio.wisodev.chatgpt.site","0.4.0",extension,[](const clap_host_t*){state.restart=true;},[](const clap_host_t*){},[](const clap_host_t*){state.callback=true;}};const auto*plugin=factory->create_plugin(factory,&host,descriptor->id);require(plugin&&plugin->init(plugin),"CLAP plug-in init failed");auto saved=readState(options.stateIn,"clap",descriptor->id);load(plugin,saved);
std::vector<clap_event_param_value_t>params;auto*parameters=(const clap_plugin_params_t*)plugin->get_extension(plugin,CLAP_EXT_PARAMS);for(const auto&arg:options.parameters){auto eq=arg.find('=');require(eq!=std::string::npos&&parameters,"Expected supported parameter-id=value");clap_id id=std::stoul(arg.substr(0,eq));double value=std::stod(arg.substr(eq+1));bool found=false;for(uint32_t j=0;j<parameters->count(plugin);j++){clap_param_info_t info{};parameters->get_info(plugin,j,&info);if(info.id==id){require(std::isfinite(value)&&value>=info.min_value&&value<=info.max_value,"Parameter out of range");clap_event_param_value_t e{};e.header={sizeof(e),0,CLAP_CORE_EVENT_SPACE_ID,CLAP_EVENT_PARAM_VALUE,0};e.param_id=id;e.cookie=info.cookie;e.note_id=-1;e.port_index=-1;e.channel=-1;e.key=-1;e.value=value;params.push_back(e);found=true;break;}}require(found,"Unknown parameter id");}
clap_input_events_t events={&params,[](const clap_input_events_t*l)->uint32_t{return ((std::vector<clap_event_param_value_t>*)l->ctx)->size();},[](const clap_input_events_t*l,uint32_t i)->const clap_event_header_t*{auto*v=(std::vector<clap_event_param_value_t>*)l->ctx;return i<v->size()?&(*v)[i].header:nullptr;}};clap_output_events_t outputs={nullptr,[](const clap_output_events_t*,const clap_event_header_t*){return true;}};
if(options.edit){
#ifdef AURALIS_X11
 auto*gui=(const clap_plugin_gui_t*)plugin->get_extension(plugin,CLAP_EXT_GUI);require(gui&&gui->is_api_supported(plugin,CLAP_WINDOW_API_X11,false),"Plug-in does not expose an embedded X11 editor");require(gui->create(plugin,CLAP_WINDOW_API_X11,false),"Cannot create native editor");uint32_t width=640,height=480;require(gui->get_size(plugin,&width,&height)&&width>=16&&height>=16&&width<=8192&&height<=8192,"Invalid editor dimensions");{NativeWindow window(descriptor->name,width,height);state.window=&window;clap_window_t parent{};parent.api=CLAP_WINDOW_API_X11;parent.x11=window.window;require(gui->set_parent(plugin,&parent)&&gui->show(plugin),"Cannot attach native editor");if(parameters&&!params.empty()){parameters->flush(plugin,&events,&outputs);params.clear();}std::cout<<"EDITOR_READY\n"<<std::flush;bool canceled=false;auto*timers=(const clap_plugin_timer_support_t*)plugin->get_extension(plugin,CLAP_EXT_TIMER_SUPPORT);auto*fds=(const clap_plugin_posix_fd_support_t*)plugin->get_extension(plugin,CLAP_EXT_POSIX_FD_SUPPORT);
 while(!window.closed&&!state.closed){if(auto size=state.sizeRequest.exchange(0))window.resize(size>>32,size&0xffffffff);auto visibility=state.visibility.exchange(0);if(visibility==1)XMapRaised(window.display,window.window);if(visibility==2)XUnmapWindow(window.display,window.window);window.events([&](const XEvent&e){if(e.type==ConfigureNotify&&e.xconfigure.window==window.window&&gui->can_resize(plugin)&&(uint32_t(e.xconfigure.width)!=window.width||uint32_t(e.xconfigure.height)!=window.height)){uint32_t w=e.xconfigure.width,h=e.xconfigure.height;if(gui->adjust_size(plugin,&w,&h)&&gui->set_size(plugin,w,h)){window.width=w;window.height=h;if(w!=uint32_t(e.xconfigure.width)||h!=uint32_t(e.xconfigure.height))window.resize(w,h);}}});if(state.callback.exchange(false))plugin->on_main_thread(plugin);if(state.flush.exchange(false)&&parameters)parameters->flush(plugin,&events,&outputs);const auto now=monotonicMs();std::vector<clap_id>due;for(auto&[id,t]:state.timers)if(now>=t.next){t.next=now+t.period;due.push_back(id);}for(auto id:due)if(timers&&state.timers.count(id))timers->on_timer(plugin,id);std::vector<pollfd>polls;for(const auto&[fd,flags]:state.fds)polls.push_back({fd,short((flags&CLAP_POSIX_FD_READ?POLLIN:0)|(flags&CLAP_POSIX_FD_WRITE?POLLOUT:0)),0});if(!polls.empty()&&poll(polls.data(),polls.size(),0)>0)for(const auto&p:polls)if(p.revents&&fds&&state.fds.count(p.fd))fds->on_fd(plugin,p.fd,(p.revents&POLLIN?CLAP_POSIX_FD_READ:0)|(p.revents&POLLOUT?CLAP_POSIX_FD_WRITE:0)|(p.revents&(POLLERR|POLLHUP)?CLAP_POSIX_FD_ERROR:0));const auto command=controlCommand();if(command.find("cancel")!=std::string::npos){canceled=true;break;}if(command.find("save")!=std::string::npos)break;poll(nullptr,0,8);}
 if(!canceled){if(parameters)parameters->flush(plugin,&events,&outputs);save(plugin,saved,options.stateOut);}gui->hide(plugin);gui->destroy(plugin);state.window=nullptr;if(canceled){plugin->destroy(plugin);entry->deinit();dlclose(lib);return 2;}}
#else
 throw std::runtime_error("This host was built without native X11 editors; rebuild with AURALIS_X11=1");
#endif
}else{WaveReader reader(options.input.c_str());auto*ports=(const clap_plugin_audio_ports_t*)plugin->get_extension(plugin,CLAP_EXT_AUDIO_PORTS);require(ports&&ports->count(plugin,true)==1&&ports->count(plugin,false)==1,"Host supports one main input/output bus");for(bool input:{true,false}){clap_audio_port_info_t info{};require(ports->get(plugin,0,input,&info)&&info.channel_count==reader.channels,"Plug-in channel topology differs from WAV");}auto*offline=(const clap_plugin_render_t*)plugin->get_extension(plugin,CLAP_EXT_RENDER);if(offline)require(offline->set(plugin,CLAP_RENDER_OFFLINE),"Offline mode rejected");require(plugin->activate(plugin,reader.rate,1,512),"CLAP activate failed");auto*latencyExt=(const clap_plugin_latency_t*)plugin->get_extension(plugin,CLAP_EXT_LATENCY);uint32_t latency=latencyExt?latencyExt->get(plugin):0;state.audio=true;require(plugin->start_processing(plugin),"CLAP start failed");state.audio=false;
 render(reader,options.output.c_str(),latency,[&](Channels&in,Channels&out,uint32_t n,uint64_t frame){std::vector<float*>ip,op;for(auto&c:in)ip.push_back(c.data());for(auto&c:out)op.push_back(c.data());clap_audio_buffer_t input{},output{};input.data32=ip.data();input.channel_count=in.size();output.data32=op.data();output.channel_count=out.size();clap_process_t process{};process.steady_time=frame;process.frames_count=n;process.audio_inputs=&input;process.audio_outputs=&output;process.audio_inputs_count=1;process.audio_outputs_count=1;process.in_events=&events;process.out_events=&outputs;state.audio=true;auto status=plugin->process(plugin,&process);state.audio=false;require(status!=CLAP_PROCESS_ERROR,"CLAP process failed");params.clear();if(state.callback.exchange(false))plugin->on_main_thread(plugin);require(!state.restart,"Plug-in requested restart during frozen render");});state.audio=true;plugin->stop_processing(plugin);state.audio=false;plugin->deactivate(plugin);if(!options.stateOut.empty())save(plugin,saved,options.stateOut);std::cout<<"CLAP render complete; latency compensated: "<<latency<<" frames\n";}
plugin->destroy(plugin);entry->deinit();dlclose(lib);return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
