#include "vst3-state.hpp"
#include <dlfcn.h>
#include <memory>
int main(int argc,char**argv){try{HostOptions options(argc,argv);std::unique_ptr<WaveReader>readerPtr;if(!options.edit)readerPtr=std::make_unique<WaveReader>(options.input.c_str());const uint32_t sampleRate=readerPtr?readerPtr->rate:48000,channelCount=readerPtr?readerPtr->channels:2;void*lib=dlopen(argv[1],RTLD_NOW|RTLD_LOCAL);require(lib,"Cannot load VST3 module binary");auto entry=(bool(*)(void*))dlsym(lib,"ModuleEntry");auto exit=(bool(*)())dlsym(lib,"ModuleExit");require(entry&&exit&&entry(lib),"VST3 ModuleEntry failed");auto getFactory=(IPluginFactory*(*)())dlsym(lib,"GetPluginFactory");require(getFactory,"Missing GetPluginFactory");IPluginFactory*factory=getFactory();require(factory,"No factory");HostApplication host;
#ifdef AURALIS_X11
 PlugFrame frame(nullptr,nullptr);host.context=static_cast<Linux::IRunLoop*>(&frame);
#endif
 IPluginFactory3*factory3=nullptr;if(factory->queryInterface(IPluginFactory3::iid,(void**)&factory3)==kResultOk){factory3->setHostContext(&host);factory3->release();}IComponent*component=nullptr;std::string identity;for(int i=0;i<factory->countClasses();i++){PClassInfo info{};if(factory->getClassInfo(i,&info)==kResultOk&&!strcmp(info.category,kVstAudioEffectClass)){char hex[33]={};for(int j=0;j<16;j++)std::sprintf(hex+2*j,"%02x",(unsigned char)info.cid[j]);if(!options.pluginId.empty()&&options.pluginId!=hex)continue;identity=hex;require(factory->createInstance(info.cid,IComponent::iid,(void**)&component)==kResultOk&&component,"Cannot instantiate effect");break;}}require(component,"No audio effect class");component->setIoMode(kOfflineProcessing);require(component->initialize(&host)==kResultOk,"VST3 initialize failed");IAudioProcessor*processor=nullptr;require(component->queryInterface(IAudioProcessor::iid,(void**)&processor)==kResultOk,"No audio processor");require(processor->canProcessSampleSize(kSample32)==kResultOk,"Float32 unsupported");Parameters parameters,outputParameters;for(const auto&arg:options.parameters){auto eq=arg.find('=');require(eq!=std::string::npos,"Expected parameter-id=value");ParamQueue q;q.id=std::stoul(arg.substr(0,eq));q.value=std::stod(arg.substr(eq+1));require(std::isfinite(q.value)&&q.value>=0&&q.value<=1,"VST3 parameter must be normalized0..1");parameters.data.push_back(q);}IEditController*controller=nullptr;bool separate=false;IConnectionPoint*componentConnection=nullptr,*controllerConnection=nullptr;ComponentHandler handler;handler.pending=&parameters;if(component->queryInterface(IEditController::iid,(void**)&controller)!=kResultOk){TUID controllerId{};if(component->getControllerClassId(controllerId)==kResultOk&&factory->createInstance(controllerId,IEditController::iid,(void**)&controller)==kResultOk&&controller){require(controller->initialize(&host)==kResultOk,"Controller initialization failed");separate=true;}}if(controller){controller->setComponentHandler(&handler);component->queryInterface(IConnectionPoint::iid,(void**)&componentConnection);controller->queryInterface(IConnectionPoint::iid,(void**)&controllerConnection);if(componentConnection&&controllerConnection){componentConnection->connect(controllerConnection);controllerConnection->connect(componentConnection);}}auto saved=readState(options.stateIn,"vst3",identity);loadVst(component,controller,saved);if(controller)for(const auto&q:parameters.data)controller->setParamNormalized(q.id,q.value);
require(component->getBusCount(kAudio,kInput)==1&&component->getBusCount(kAudio,kOutput)==1,"Host supports one main input/output bus");SpeakerArrangement arrangement=channelCount==1?SpeakerArr::kMono:SpeakerArr::kStereo;require(processor->setBusArrangements(&arrangement,1,&arrangement,1)==kResultOk,"Bus arrangement rejected");for(auto direction:{kInput,kOutput}){BusInfo bus{};require(component->getBusInfo(kAudio,direction,0,bus)==kResultOk&&bus.channelCount==channelCount,"Bus channel mismatch");require(component->activateBus(kAudio,direction,0,true)==kResultOk,"Cannot activate bus");}ProcessSetup setup{kOffline,kSample32,512,double(sampleRate)};require(processor->setupProcessing(setup)==kResultOk,"Setup processing failed");handler.restart=false;require(component->setActive(true)==kResultOk,"Activation failed");require(processor->setProcessing(true)==kResultOk,"setProcessing failed");uint32_t latency=processor->getLatencySamples();EmptyEvents inputEvents,outputEvents;auto processBlock=[&](Channels&in,Channels&out,uint32_t n,uint64_t frame){std::vector<float*>ip,op;for(auto&c:in)ip.push_back(c.data());for(auto&c:out)op.push_back(c.data());AudioBusBuffers input{},output{};input.numChannels=in.size();input.channelBuffers32=ip.data();output.numChannels=out.size();output.channelBuffers32=op.data();ProcessContext context{};context.sampleRate=sampleRate;context.projectTimeSamples=frame;context.continousTimeSamples=frame;context.state=ProcessContext::kPlaying|ProcessContext::kContTimeValid;ProcessData data{};data.processMode=kOffline;data.symbolicSampleSize=kSample32;data.numSamples=n;data.numInputs=1;data.numOutputs=1;data.inputs=&input;data.outputs=&output;data.inputParameterChanges=&parameters;data.outputParameterChanges=&outputParameters;data.inputEvents=&inputEvents;data.outputEvents=&outputEvents;data.processContext=&context;require(processor->process(data)==kResultOk,"VST3 processing failed");parameters.data.clear();if(controller)for(auto&q:outputParameters.data)controller->setParamNormalized(q.id,q.value);outputParameters.data.clear();};
if(options.edit){
#ifdef AURALIS_X11
 require(controller,"Plug-in has no edit controller");auto*view=controller->createView(ViewType::kEditor);require(view&&view->isPlatformTypeSupported(kPlatformTypeX11EmbedWindowID)==kResultOk,"Plug-in has no X11 editor");ViewRect size;require(view->getSize(&size)==kResultOk&&size.getWidth()>=16&&size.getHeight()>=16&&size.getWidth()<=8192&&size.getHeight()<=8192,"Invalid editor size");{NativeWindow window("Auralis VST3 editor",size.getWidth(),size.getHeight());frame.window=&window;frame.view=view;require(view->setFrame(&frame)==kResultOk&&view->attached((void*)(uintptr_t)window.window,kPlatformTypeX11EmbedWindowID)==kResultOk,"Cannot attach VST3 editor");std::cout<<"EDITOR_READY\n"<<std::flush;Channels silence(2,std::vector<float>(512)),out=silence;uint64_t position=0;bool canceled=false;while(!window.closed){frame.pump();window.events([&](const XEvent&event){view->getSize(&size);if(event.type==ConfigureNotify&&event.xconfigure.window==window.window&&(event.xconfigure.width!=size.getWidth()||event.xconfigure.height!=size.getHeight())){ViewRect next(0,0,event.xconfigure.width,event.xconfigure.height);if(view->canResize()==kResultOk&&view->checkSizeConstraint(&next)==kResultOk){size=next;view->onSize(&size);}window.resize(size.getWidth(),size.getHeight());}if(event.type==FocusIn||event.type==FocusOut)view->onFocus(event.type==FocusIn);if(event.type==KeyPress||event.type==KeyRelease){auto key=event.xkey;char chars[8]={};KeySym sym;int n=XLookupString(&key,chars,7,&sym,nullptr);int16 modifiers=(key.state&ShiftMask?kShiftKey:0)|(key.state&ControlMask?kCommandKey:0)|(key.state&Mod1Mask?kAlternateKey:0);if(event.type==KeyPress)view->onKeyDown(n?(unsigned char)chars[0]:0,vstKey(sym),modifiers);else view->onKeyUp(n?(unsigned char)chars[0]:0,vstKey(sym),modifiers);}});processBlock(silence,out,512,position);position+=512;require(!handler.restart,"Plug-in requested unsupported bus or component reload; saved project state retained");auto command=controlCommand();if(command.find("cancel")!=std::string::npos){canceled=true;break;}if(command.find("save")!=std::string::npos)break;poll(nullptr,0,10);}processBlock(silence,out,512,position);view->removed();view->setFrame(nullptr);view->release();frame.view=nullptr;frame.window=nullptr;processor->setProcessing(false);component->setActive(false);if(!canceled)saveVst(component,controller,saved,options.stateOut);if(canceled)std::cout<<"EDITOR_CANCELED\n";}
#else
 throw std::runtime_error("This host was built without X11 editors; rebuild with AURALIS_X11=1");
#endif
}else{render(*readerPtr,options.output.c_str(),latency,processBlock);processor->setProcessing(false);component->setActive(false);if(!options.stateOut.empty())saveVst(component,controller,saved,options.stateOut);}
if(componentConnection&&controllerConnection){componentConnection->disconnect(controllerConnection);controllerConnection->disconnect(componentConnection);}if(componentConnection)componentConnection->release();if(controllerConnection)controllerConnection->release();if(controller){controller->setComponentHandler(nullptr);if(separate)controller->terminate();controller->release();}
component->terminate();processor->release();component->release();factory->release();exit();dlclose(lib);std::cout<<"VST3 render complete; latency compensated: "<<latency<<" frames\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
