#pragma once
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <functional>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>
using Channels=std::vector<std::vector<float>>;
inline void require(bool ok,const char* message){if(!ok)throw std::runtime_error(message);}
inline uint32_t u32(const unsigned char*p){return uint32_t(p[0])|(uint32_t(p[1])<<8)|(uint32_t(p[2])<<16)|(uint32_t(p[3])<<24);}
inline uint16_t u16(const unsigned char*p){return p[0]|(p[1]<<8);}
struct WaveReader{std::ifstream file;uint32_t rate=0;uint16_t channels=0,bits=0,format=0,align=0;uint64_t frames=0,position=0;WaveReader(const char*path):file(path,std::ios::binary){unsigned char h[12];file.read((char*)h,12);require(file.good()&&!memcmp(h,"RIFF",4)&&!memcmp(h+8,"WAVE",4),"Expected RIFF WAV");bool found=false;while(file){unsigned char c[8];file.read((char*)c,8);if(!file)break;uint32_t size=u32(c+4);auto begin=file.tellg();if(!memcmp(c,"fmt ",4)){require(size>=16&&size<1048576,"Invalid fmt");std::vector<unsigned char> f(size);file.read((char*)f.data(),size);format=u16(f.data());channels=u16(f.data()+2);rate=u32(f.data()+4);align=u16(f.data()+12);bits=u16(f.data()+14);if(format==65534&&size>=40)format=u16(f.data()+24);}else if(!memcmp(c,"data",4)){require(channels>0&&channels<=2&&rate>=8000&&rate<=384000&&(format==1||format==3)&&(bits==16||bits==24||bits==32)&&align==channels*bits/8&&size%align==0,"Unsupported WAV");require(format!=3||bits==32,"Float WAV must be32bit");frames=size/align;found=true;break;}file.seekg(begin+std::streamoff(size+(size&1)));}require(found,"Missing WAV data");}
void read(Channels&out,uint32_t n){for(auto&c:out)std::fill(c.begin(),c.end(),0);uint32_t count=std::min<uint64_t>(n,frames-position);std::vector<unsigned char>b(count*align);file.read((char*)b.data(),b.size());require(file.gcount()==std::streamsize(b.size()),"Truncated WAV");for(uint32_t i=0;i<count;i++)for(uint32_t c=0;c<channels;c++){const auto*p=b.data()+i*align+c*bits/8;float v=0;if(format==3)memcpy(&v,p,4);else if(bits==16)v=int16_t(u16(p))/32768.f;else if(bits==24){int32_t x=p[0]|(p[1]<<8)|(p[2]<<16);if(x&0x800000)x-=0x1000000;v=x/8388608.f;}else v=int32_t(u32(p))/2147483648.f;out[c][i]=std::isfinite(v)?v:0;}position+=count;}};
struct WaveWriter{std::ofstream file;WaveWriter(const char*path,uint32_t rate,uint16_t channels,uint64_t frames):file(path,std::ios::binary){require(frames*channels*4<=0xffffffff-36,"WAV exceeds4GiB");unsigned char h[44]={};memcpy(h,"RIFF",4);memcpy(h+8,"WAVEfmt ",8);memcpy(h+36,"data",4);auto set32=[&](int o,uint32_t n){for(int i=0;i<4;i++)h[o+i]=(n>>(i*8))&255;};auto set16=[&](int o,uint16_t n){h[o]=n&255;h[o+1]=n>>8;};set32(4,36+frames*channels*4);set32(16,16);set16(20,3);set16(22,channels);set32(24,rate);set32(28,rate*channels*4);set16(32,channels*4);set16(34,32);set32(40,frames*channels*4);file.write((char*)h,44);require(file.good(),"Cannot write output");}void write(const Channels&data,uint32_t from,uint32_t count){for(uint32_t i=from;i<from+count;i++)for(const auto&c:data){float v=c[i];require(std::isfinite(v),"Plug-in emitted non-finite audio");file.write((const char*)&v,4);}require(file.good(),"Output write failed");}};
inline void render(WaveReader&r,const char*output,uint32_t latency,const std::function<void(Channels&,Channels&,uint32_t,uint64_t)>&process){require(latency<=r.rate*10,"Plug-in latency exceeds10seconds");WaveWriter w(output,r.rate,r.channels,r.frames);Channels input(r.channels,std::vector<float>(512)),out=input;uint64_t total=r.frames+latency,written=0,skip=latency;for(uint64_t at=0;at<total;at+=512){uint32_t n=std::min<uint64_t>(512,total-at);r.read(input,n);for(auto&c:out)std::fill(c.begin(),c.end(),0);process(input,out,n,at);uint32_t trim=std::min<uint64_t>(n,skip);skip-=trim;uint32_t count=std::min<uint64_t>(n-trim,r.frames-written);w.write(out,trim,count);written+=count;}require(written==r.frames,"Output frame count mismatch");}
