#pragma once
#include "../vst3-state.hpp"
static const FUID controllerCid(0xB0123456,0xC1234567,0xD1234567,0xE1234567);
struct Controller;
#ifdef AURALIS_X11
struct FixtureView:IPlugView,Linux::IEventHandler{Controller*controller;Display*display=nullptr;Window child=0;IPlugFrame*frame=nullptr;Linux::IRunLoop*loop=nullptr;int width=400,height=180;uint32 refs=1;FixtureView(Controller*c):controller(c){}tresult PLUGIN_API queryInterface(const TUID iid,void**out)override{if(FUnknownPrivate::iidEqual(iid,IPlugView::iid)||FUnknownPrivate::iidEqual(iid,FUnknown::iid))*out=static_cast<IPlugView*>(this);else if(FUnknownPrivate::iidEqual(iid,Linux::IEventHandler::iid))*out=static_cast<Linux::IEventHandler*>(this);else{*out=nullptr;return kNoInterface;}addRef();return kResultOk;}uint32 PLUGIN_API addRef()override{return ++refs;}uint32 PLUGIN_API release()override{auto n=--refs;if(!n)delete this;return n;}tresult PLUGIN_API isPlatformTypeSupported(FIDString t)override{return !strcmp(t,kPlatformTypeX11EmbedWindowID)?kResultOk:kResultFalse;}tresult PLUGIN_API attached(void*p,FIDString)override{display=XOpenDisplay(nullptr);if(!display||!frame)return kResultFalse;frame->queryInterface(Linux::IRunLoop::iid,(void**)&loop);if(!loop)return kResultFalse;child=XCreateSimpleWindow(display,(Window)(uintptr_t)p,0,0,400,180,0,0,0x354251);XSelectInput(display,child,ButtonPressMask|ExposureMask);loop->registerEventHandler(this,ConnectionNumber(display));XMapWindow(display,child);XFlush(display);return kResultOk;}tresult PLUGIN_API removed()override{if(loop){loop->unregisterEventHandler(this);loop->release();loop=nullptr;}if(display){XDestroyWindow(display,child);XCloseDisplay(display);display=nullptr;}return kResultOk;}tresult PLUGIN_API onWheel(float)override{return kResultFalse;}tresult PLUGIN_API onKeyDown(char16,int16,int16)override{return kResultFalse;}tresult PLUGIN_API onKeyUp(char16,int16,int16)override{return kResultFalse;}tresult PLUGIN_API getSize(ViewRect*r)override{*r=ViewRect(0,0,width,height);return kResultOk;}tresult PLUGIN_API onSize(ViewRect*r)override{width=r->getWidth();height=r->getHeight();if(child)XResizeWindow(display,child,width,height);return kResultOk;}tresult PLUGIN_API onFocus(TBool)override{return kResultOk;}tresult PLUGIN_API setFrame(IPlugFrame*f)override{frame=f;return kResultOk;}tresult PLUGIN_API canResize()override{return kResultFalse;}tresult PLUGIN_API checkSizeConstraint(ViewRect*)override{return kResultOk;}void PLUGIN_API onFDIsSet(Linux::FileDescriptor)override;};
namespace Steinberg{DEF_CLASS_IID(Linux::IEventHandler)}
#endif
struct Controller:IEditController{uint32 refs=1;double value=.5;uint32 color=0;IComponentHandler*handler=nullptr;tresult PLUGIN_API queryInterface(const TUID iid,void**out)override{if(FUnknownPrivate::iidEqual(iid,IEditController::iid)||FUnknownPrivate::iidEqual(iid,FUnknown::iid)){*out=static_cast<IEditController*>(this);addRef();return kResultOk;}*out=nullptr;return kNoInterface;}uint32 PLUGIN_API addRef()override{return ++refs;}uint32 PLUGIN_API release()override{auto n=--refs;if(!n)delete this;return n;}tresult PLUGIN_API initialize(FUnknown*)override{return kResultOk;}tresult PLUGIN_API terminate()override{return kResultOk;}tresult PLUGIN_API setComponentState(IBStream*s)override{return s->read(&value,sizeof(value));}tresult PLUGIN_API setState(IBStream*s)override{return s->read(&color,sizeof(color));}tresult PLUGIN_API getState(IBStream*s)override{return s->write(&color,sizeof(color));}int32 PLUGIN_API getParameterCount()override{return 1;}tresult PLUGIN_API getParameterInfo(int32 i,ParameterInfo&p)override{if(i)return kInvalidArgument;p={};p.id=0;p.defaultNormalizedValue=.5;return kResultOk;}tresult PLUGIN_API getParamStringByValue(ParamID,ParamValue,String128)override{return kResultFalse;}tresult PLUGIN_API getParamValueByString(ParamID,TChar*,ParamValue&)override{return kResultFalse;}ParamValue PLUGIN_API normalizedParamToPlain(ParamID,ParamValue v)override{return v;}ParamValue PLUGIN_API plainParamToNormalized(ParamID,ParamValue v)override{return v;}ParamValue PLUGIN_API getParamNormalized(ParamID)override{return value;}tresult PLUGIN_API setParamNormalized(ParamID,ParamValue v)override{value=v;return kResultOk;}tresult PLUGIN_API setComponentHandler(IComponentHandler*h)override{handler=h;return kResultOk;}IPlugView*PLUGIN_API createView(FIDString type)override{
#ifdef AURALIS_X11
return !strcmp(type,ViewType::kEditor)?new FixtureView(this):nullptr;
#else
(void)type;return nullptr;
#endif
}};
#ifdef AURALIS_X11
void FixtureView::onFDIsSet(Linux::FileDescriptor){while(XPending(display)){XEvent e;XNextEvent(display,&e);if(e.type==ButtonPress){controller->value=.75;controller->color=42;controller->handler->beginEdit(0);controller->handler->performEdit(0,.75);controller->handler->endEdit(0);ViewRect next(0,0,600,240);frame->resizeView(this,&next);XClearWindow(display,child);}if(e.type==Expose){GC gc=XCreateGC(display,child,0,nullptr);XSetForeground(display,gc,0xc7e4fa);const char*label=controller->value>.6?"Gain 0.75 saved":"Click to set gain 0.75";XDrawString(display,child,gc,20,60,label,strlen(label));XFreeGC(display,gc);}}XFlush(display);}
#endif
