import {app,BrowserWindow,dialog,Menu,screen,utilityProcess} from 'electron';
import {readFile,mkdir} from 'node:fs/promises';
import {writeFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
let service,main,origin='',quitting=false,layout={},audioGranted=false;
const webPreferences={sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true,webviewTag:false};
function owned(url){try{return new URL(url).origin===origin;}catch{return false;}}
function bounds(key,defaults){const b=layout[key];return b&&[b.x,b.y,b.width,b.height].every(Number.isSafeInteger)&&b.width>=280&&b.height>=300&&b.width<=16384&&b.height<=16384&&screen.getAllDisplays().some(d=>b.x+b.width>d.workArea.x&&b.x<d.workArea.x+d.workArea.width&&b.y+b.height>d.workArea.y&&b.y<d.workArea.y+d.workArea.height)?{...defaults,...b}:defaults;}
function remember(win,key){if(!win.isDestroyed()&&!win.isMinimized()){layout[key]=win.getNormalBounds();try{writeFileSync(path.join(app.getPath('userData'),'window-layout.json'),JSON.stringify(layout));}catch{}}}
function configure(win,isMain=false){let key=isMain?'main':'tool';win.webContents.on('will-prevent-unload',event=>{const answer=dialog.showMessageBoxSync(win,{type:'question',buttons:['Keep editing','Close without saving'],defaultId:0,cancelId:0,title:'Unsaved project',message:'Close this workspace and discard unsaved changes?'});if(answer===1)event.preventDefault();});win.webContents.on('will-navigate',(event,url)=>{if(!owned(url))event.preventDefault();});win.webContents.on('will-redirect',(event,url)=>{if(!owned(url))event.preventDefault();});
 win.webContents.setWindowOpenHandler(({url})=>{let u;try{u=new URL(url);}catch{return {action:'deny'};}if(!isMain||!owned(url)||u.pathname!=='/studio/detached.html'||!/^#[\w-]{20,80}$/.test(u.hash))return {action:'deny'};return {action:'allow',overrideBrowserWindowOptions:{width:850,height:760,minWidth:280,minHeight:300,backgroundColor:'#263745',autoHideMenuBar:true,webPreferences}};});
 win.webContents.on('did-create-window',child=>configure(child));win.on('page-title-updated',(_,title)=>{const kind=title.match(/^Auralis · (master|meters|clips|markers|inspector)$/)?.[1];if(!isMain&&kind&&key!==kind){key=kind;win.setBounds(bounds(key,win.getBounds()));}});win.on('close',()=>remember(win,key));
 win.webContents.session.setPermissionCheckHandler((contents,permission,requestOrigin,details)=>owned(requestOrigin)&&owned(contents?.getURL()||'')&&(permission==='fileSystem'||permission==='media'&&audioGranted&&details.mediaType==='audio'));
 win.webContents.session.setPermissionRequestHandler(async(contents,permission,callback,details)=>{if(!owned(contents.getURL())||!owned(details.requestingUrl||contents.getURL()))return callback(false);if(permission==='fileSystem')return callback(true);if(permission!=='media'||!details.mediaTypes?.length||details.mediaTypes.some(t=>t!=='audio'))return callback(false);if(audioGranted)return callback(true);const target=BrowserWindow.fromWebContents(contents);try{const r=await dialog.showMessageBox(target,{type:'question',buttons:['Allow microphone','Cancel'],defaultId:1,cancelId:1,title:'Audio input',message:'Allow Auralis to capture your selected audio input?',detail:'Recording and device checks use this input. Audio stays in your local session until you explicitly save or export it.'});audioGranted=r.response===0;callback(audioGranted);}catch{callback(false);}});
}
async function startService(){return new Promise((resolve,reject)=>{service=utilityProcess.fork(path.join(root,'server/standalone.mjs'),[],{cwd:root,env:{...process.env,AURALIS_PORT:process.env.AURALIS_DESKTOP_PORT||'47831',AURALIS_DATA_DIR:path.join(app.getPath('userData'),'sessions')},stdio:'pipe',serviceName:'Auralis audio and project service'});let output='',ready=false;const timeout=setTimeout(()=>{service.kill();reject(Error('Local service startup timed out.'));},15000);service.stdout.on('data',bytes=>{output=(output+bytes).slice(-4096);const match=output.match(/Auralis Studio: (http:\/\/127\.0\.0\.1:\d+)/);if(match&&!ready){ready=true;clearTimeout(timeout);resolve(match[1]);}});service.stderr.on('data',bytes=>{output=(output+bytes).slice(-4096);});service.on('exit',code=>{clearTimeout(timeout);if(!ready)reject(Error('Local service exited: '+output));else if(!quitting){dialog.showErrorBox('Auralis local service stopped','The project service stopped unexpectedly. Restart Auralis to reopen saved sessions.');app.quit();}});});}
if(!app.requestSingleInstanceLock())app.quit();else{
 app.on('second-instance',()=>{if(main){if(main.isMinimized())main.restore();main.focus();}});
 app.whenReady().then(async()=>{await mkdir(app.getPath('userData'),{recursive:true});try{layout=JSON.parse(await readFile(path.join(app.getPath('userData'),'window-layout.json'),'utf8'));}catch{}if(!layout||typeof layout!=='object'||Array.isArray(layout))layout={};origin=await startService();Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'Auralis',submenu:[{role:'about'},{type:'separator'},{role:'quit'}]},{label:'Window',submenu:[{role:'minimize'},{role:'zoom'},{role:'togglefullscreen'}]}]));main=new BrowserWindow({...bounds('main',{width:1500,height:960}),minWidth:1000,minHeight:650,title:'Auralis Studio',backgroundColor:'#263745',webPreferences});configure(main,true);await main.loadURL(origin+'/studio/index.html');}).catch(error=>{dialog.showErrorBox('Auralis could not start',error.message);app.quit();});
 app.on('will-quit',()=>{quitting=true;service?.kill();});app.on('window-all-closed',()=>app.quit());
}
